server:
  port: 8080

STATS_SERVER_URL: "http://localhost:9090"

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always

logging:
  level:
    root: debug
