DROP TABLE IF EXISTS categories;


CREATE TABLE IF NOT EXISTS categories
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name        VARCHAR(255) UNIQUE                                 NOT NULL,
);

CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name    VARCHAR(255)                                        NOT NULL,
    email   VARCHAR(512) UNIQUE                                 NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    event_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    category_id        BIGINT                                              NOT NULL,
    annotation         VARCHAR(2000)                                       NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    description        VARCHAR(7000)                                       NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    initiator_id       BIGINT                                              NOT NULL,
    location_id        BIGINT,
    paid               BOOLEAN                                             NOT NULL,
    participant_limit  INTEGER,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN                                             NOT NULL,
    state              VARCHAR(120)                                        NOT NULL,
    title              VARCHAR(120)                                        NOT NULL,
    views              BIGINT
);

CREATE TABLE IF NOT EXISTS locations
(
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    lat         FLOAT                                               NOT NULL,
    lon         FLOAT                                               NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations
(
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    pinned         BOOLEAN                                             NOT NULL,
    title          VARCHAR(50)                                         NOT NULL
);

CREATE TABLE IF NOT EXISTS event_compilations
(
    event_compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    compilation_id       BIGINT                                              NOT NULL,
    event_id             BIGINT                                              NOT NULL
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    event_id     BIGINT                                              NOT NULL,
    requester_id BIGINT                                              NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    status       VARCHAR                                             NOT NULL
);


