DROP TABLE IF EXISTS categories;


CREATE TABLE IF NOT EXISTS categories
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name varchar(255)    UNIQUE                             NOT NULL,
);

CREATE TABLE IF NOT EXISTS users
(
    id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name  varchar(255)                                        NOT NULL,
    email varchar(512) UNIQUE                                 NOT NULL
);



