DROP TABLE IF EXISTS endpoints;
DROP TABLE IF EXISTS visitors;


CREATE TABLE IF NOT EXISTS endpoints
(
    id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    app varchar(255)                                        NOT NULL,
    uri varchar(512)                                        NOT NULL,
    UNIQUE (app, uri)
);

CREATE TABLE IF NOT EXISTS visitors
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip          varchar(512)                NOT NULL,
    timestamp   timestamp without time zone NOT NULL,
    endpoint_id bigint
);

ALTER TABLE visitors
    DROP CONSTRAINT IF EXISTS fk_visitors_to_endpoints;

ALTER TABLE visitors
    ADD CONSTRAINT fk_visitors_to_endpoints FOREIGN KEY (endpoint_id) REFERENCES endpoints (id)
        ON DELETE CASCADE ON UPDATE CASCADE;