DROP TABLE IF EXISTS endpoints;
DROP TABLE IF EXISTS visitors;


CREATE TABLE IF NOT EXISTS endpoints
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    app VARCHAR(255) UNIQUE                                 NOT NULL,
    uri  VARCHAR(512)                                        NOT NULL
);

CREATE TABLE IF NOT EXISTS visitors
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip         VARCHAR(512)                NOT NULL,
    timestamp  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    endpoint_id BIGINT
);

ALTER TABLE visitors
    DROP CONSTRAINT IF EXISTS fk_visitors_to_endpoints;

ALTER TABLE visitors
    ADD CONSTRAINT fk_visitors_to_endpoints FOREIGN KEY (endpoint_id) REFERENCES endpoints (id)
        ON DELETE CASCADE ON UPDATE CASCADE;