DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS statistics;


CREATE TABLE IF NOT EXISTS services
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(255) UNIQUE                                 NOT NULL,
    uri  VARCHAR(512)                                        NOT NULL
);

CREATE TABLE IF NOT EXISTS statistics
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip         VARCHAR(512)                NOT NULL,
    timestamp  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    service_id BIGINT
);

ALTER TABLE statistics
    DROP CONSTRAINT IF EXISTS fk_statistics_to_services;

ALTER TABLE statistics
    ADD CONSTRAINT fk_statistics_to_services FOREIGN KEY (service_id) REFERENCES services (id)
        ON DELETE CASCADE ON UPDATE CASCADE;